apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external
  name: external
  namespace: demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: external
  strategy: {}
  template:
    metadata:
      labels:
        app: external
    spec:
      containers:
      - image: gcr.io/twitterfeedstokafkatest/devoops_external:v1.2
        name: external
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://internal:8082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
